---
title: "exploration"
author: "Jeff Walker"
date: "1/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(nlme)
library(mvtnorm)
```


```{r fig-p-conditional}
jco_pal1 <- pal_jco()(6)
group_colors <- c(rep(jco_pal[c(2,5,4,6)], each=3))[1:length(method_list)]
group_shapes <- c(rep(c(15, 16, 17), 4))[1:length(method_list)]

subdata <- sim1_long[effect == "0",]
subdata[, d_baseline_std := abs(d_baseline)/emp.sigma]
subdata[, logit_p := ifelse(is.infinite(logit(p)), NA, logit(p))]
plot_data <- data.table(NULL)
new_d_baseline <- seq(0, 1.5, by=0.1) # uniform values of d_baseline_std for prediction
new_r_baseline <- seq(.1, .9, by=.1)

plot_data <- data.table(expand.grid(d_baseline_std = new_d_baseline, abs.r.baseline = new_r_baseline))

method_i <- "lm_base"
m1 <- glm(significant ~ abs.r.baseline + d_baseline_std, 
          family = binomial(link="logit"), 
          data=subdata[method==method_i])
plot_data[, prob.m1:=predict(m1, plot_data, type="response")]

gg1 <- ggplot(data=plot_data,
              aes(x=d_baseline_std, y=prob.m1, color=abs.r.baseline)) +
  geom_hline(yintercept = 0.05, linetype = "dashed", alpha=0.5) +
  #geom_point() +
  geom_line(aes(group = abs.r.baseline)) +
  ylab("Probability of p < 0.05") +
  xlab("Difference at Time0 (in standard deviation units)") +
  theme_pubr() +
  theme(legend.position="top") +
  guides(col = guide_legend(ncol = 4)) +
  NULL
gg1

```

## back to simple pre-post with an initial difference

```{r}
n <- 10
rho <- 0.6
alpha_1 <- 0 # treatment effect at baseline
sigma <- 5
beta_1 <- 0.5 # regression of post on pre
tau <- 0 # treatment

treatment <- rep(c("cn", "tr"), each=n)
X <- model.matrix(~treatment)
alpha <- c(10, alpha_1)
done <- FALSE
#set.seed(1)
i <- 0
while(done == FALSE){
  i <- i+1
  pre <- X%*%alpha + rnorm(n*2, mean=0, sd=sigma)
  delta <- abs(mean(pre[treatment=="tr"]) - mean(pre[treatment=="cn"]))
  if(delta > 5){done <- TRUE}
  if(i == 10^4){done <- TRUE}
}
X <- model.matrix(~pre + treatment)
beta <- c(0, beta_1, tau)
post <- pre*beta_1 + X%*%beta + rnorm(n*2, mean=0, sd=sigma*2)
sd(pre)
cor(pre, post)

qplot(x=pre, y=post, color=treatment) 
```


Generation of pre-post or AUC data using path model and using mvtnorm
```{r generation model}
n <- 10

# using path model
alpha_1 <- 0.5 # treatment effect at baseline
treatment <- rep(c("cn", "tr"), each=n)
X <- model.matrix(~treatment)
treatmenttr <- X[, "treatmenttr"]
alpha <- c(10, alpha_1)
sigma_pre <- 2
pre <- X%*%alpha + rnorm(n*2, mean=0, sd=sigma_pre)

rho <- 0.6
sigma_post <- 3
beta_1 <- rho*sigma_post/sigma_pre
tau <- 0.5 # treatment

post <- beta_1*pre + (alpha_1 + tau)*treatmenttr + sqrt(sigma_post^2 - (beta_1*sigma_pre)^2)*rnorm(n*2)

sd(pre)
sd(post)
cor(pre, post)

coef(lm(post ~ pre + treatment))

# using rmvnorm
R <- diag(2)
R[2,1] <- R[1, 2] <- rho
sigma <- c(sigma_pre, sigma_post)
Sigma <- diag(sigma)%*%R%*%diag(sigma)

beta_1_vec <- c(0, beta_1)
gtt_effects <- c(alpha_1, alpha_1 + tau)
beta <- gtt_effects + alpha_1*beta_1_vec
y_cols <- c("pre", "post")
mu <- c(10, 10)
names(mu) <- y_cols
Y <- rbind(rmvnorm(n, mu, Sigma),
           rmvnorm(n, mu+beta, Sigma))
fd <- data.table(treatment=treatment, each=n)
fd[, id:=factor(1:.N)]
fd_wide <- cbind(fd, Y)
coef(lm(pre ~ treatment, data=fd_wide))
coef(lm(post ~ pre + treatment, data=fd_wide))
fd_wide[, .(pre=mean(pre), post=mean(post)), by=treatment]

fd_long <- melt(fd_wide, id.vars=c("treatment", "id"),
                measure.vars = y_cols,
                variable.name = "time",
                value.name = "glucose")
fd_long[, time:=factor(time, y_cols)]
fit <- gls(glucose ~ factor(time)*treatment,
           data = fd_long,
           weights = varIdent(form= ~ 1 | time),
           correlation= corSymm(form=~ 1| id)
)
Sigma_fit <- getVarCov(fit, individual=fd_long[1,id])
Rho_fit <- cov2cor(Sigma_fit)
Rho_fit

# test
#      m5a <- lm(glucose_0 ~ treatment, data=fd)
#      m5b <- lm(glucose_mean ~ treatment + glucose_0, data=fd)
m5a <- lm(pre ~ treatment, data=fd_wide)
m5b <- lm(post ~ pre + treatment, data=fd_wide)
m5a_table <- coef(summary(m5a))
m5b_table <- coef(summary(m5b))
b_alpha_1 <- m5a_table["treatmenttr", "Estimate"]
b_beta_2 <- m5b_table["treatmenttr", "Estimate"]
se_b_alpha_1 <- m5a_table["treatmenttr", "Std. Error"]
se_b_beta_2 <- m5b_table["treatmenttr", "Std. Error"]
z_SED <- sqrt(se_b_alpha_1^2 + se_b_beta_2^2)
z <- (b_beta_2 - b_alpha_1)/z_SED
p_z <- (1-(pnorm(abs(z))))*2 # 2-tailed z-test for large sample
```

```{r}
n <- 10^6
b <- 0.6
a1 <- 0.9
a2 <- 0.8
A <- rnorm(n)
Y <- b*A + sqrt(1 - b^2)*rnorm(n)
astar <- a1*A + sqrt(1 - a1^2)*rnorm(n)
ystar <- a2*Y + sqrt(1 - a2^2)*rnorm(n)
var(A)
var(Y)
var(astar)
var(ystar)
a1*a2*b
coef(lm(ystar ~ astar))
cor(ystar, astar)

n <- 10^5
rho_a1 <- 0.9
rho_a2 <- 0.8
rho_b <- 0.6
sigma_A <- 2 # total variation in A
sigma_Y <- 10 # total variation in Y
sigma_astar <- 2.2 # total variation
sigma_ystar <- 20 # total variation
a1 <- rho_a1*sigma_astar/sigma_A # to astar
a2 <- rho_a2*sigma_ystar/sigma_Y # to ystar
b <- rho_b*sigma_Y/sigma_A
A <- rnorm(n, sd=sigma_A)
R2_Y <- (b*sigma_A)^2/sigma_Y^2
Y <- b*A + sqrt(1-R2_Y)*rnorm(n, sd=sigma_Y)
R2_astar <- (a1*sigma_A)^2/sigma_astar^2
astar <- a1*A + sqrt(1-R2_astar)*rnorm(n, sd=sigma_astar)
R2_ystar <- (a2*sigma_Y)^2/sigma_ystar^2
ystar <- a2*Y + sqrt(1-R2_ystar)*rnorm(n, sd=sigma_ystar)
coef(lm(ystar ~ astar))
```

```{r}
coef(lm(ystar ~ Y))
a2
```

```{r}
coef(lm(ystar ~ A))
a2*b
```

```{r}
coef(lm(astar ~ A))
a1
```

```{r}
coef(lm(ystar ~ astar))
rho_a1*rho_a2*rho_b*sigma_ystar/sigma_astar
rho_a1*sigma_A/sigma_Y*rho_a2*sigma_ystar/sigma_astar*b
b
```


```{r}
sd(A)
sd(Y)
sd(astar)
sd(ystar)
cor(A, astar)
cor(Y, ystar)
```

